[package]
name = "tcp-lab-jni"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
jni = "0.21.1"
tcp-lab-core = { path = "../tcp-lab-core" }
thiserror.workspace = true
anyhow.workspace = true
tracing.workspace = true
lazy_static = "1.5.0"

