[package]
name = "tcp-lab-ffi"
version = "0.1.0"
edition = "2024"

[lib]
name = "tcp_lab_ffi"
crate-type = ["rlib", "cdylib"]

[dependencies]
tcp-lab-abstract = { path = "../tcp-lab-abstract" }
tracing = { workspace = true }

