[package]
name = "tcp-lab-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
tcp-lab-core = { path = "../../crates/tcp-lab-core" }
anyhow = { version = "1.0", features = ["backtrace"] }
tracing = "0.1"
